apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority: /etc/kubernetes/ca/ca.pem
    server: http://{{MASTER_IP}}:8080
  name: {{CLUSTER}}
contexts:
- context:
    cluster: {{CLUSTER}}
    user: kubelet
  name: kubelet
current-context: kubelet
users:
- name: kubelet
  user:
    auth-provider:
      config:
        cluster-id: {{CLUSTER}}
      name: aws
