apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    tier: control-plane
    component: etcd
spec:
  containers:
    - name: etcd-container
      image: {{ETCD_REGISTRY}}:{{ETCD_VERSION}}
      command:
         - /usr/local/bin/etcd
         - --data-dir=/etcd-data
      ports:
        - containerPort: 2380
          hostPort: 2380
          name: serverport
        - containerPort: 2379
          hostPort: 2379
          name: clientport
      livenessProbe:
        httpGet:
          host: 127.0.0.1
          path: /health
          port: 2379
          scheme: HTTP
        initialDelaySeconds: 15
        timeoutSeconds: 15
      volumeMounts:
        - mountPath: /etcd-data
          name: varetcdata
        - mountPath: /var/log/etcd.log
          name: varlogetcd
        - mountPath: /etc/kubernetes/ca
          name: kubernetesca
  hostNetwork: true
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
  volumes:
    - name: varetcdata
      hostPath:
        path: /var/lib/etcd
    - name: varlogetcd
      hostPath:
        path: /var/log/etcd.log
    - name: kubernetesca
      hostPath:
        path: /etc/kubernetes/ca
