apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    tier: control-plane
    component: kube-apiserver
spec:
  hostNetwork: true
  containers:
    - name: kube-apiserver
      image: "k8s.gcr.io/hyperkube:{{KUBE_RELEASE}}"
      resources:
        requests:
          cpu: 250m
      command:
        - /bin/sh
        - '-c'
        - |
          exec /usr/local/bin/kube-apiserver \
               --address=0.0.0.0 \
               --insecure-bind-address=127.0.0.1 \
               --etcd-servers=http://127.0.0.1:2379 \
               --service-cluster-ip-range={{SERVICE_CIDR}} \
               --client-ca-file=/etc/kubernetes/ca/ca.pem \
               --tls-ca-file=/var/lib/kubernetes/ca/ca.pem \
               --tls-cert-file=/etc/kubernetes/ca/kubernetes.pem \
               --tls-private-key-file=/etc/kubernetes/ca/kubernetes-key.pem \
               --kubelet-certificate-authority=/etc/kubernetes/ca/ca.pem \
               --kubelet-client-certificate=/etc/kubernetes/ca/kubernetes.pem \
               --kubelet-client-key=/etc/kubernetes/ca/kubernetes-key.pem \
               --kubelet-https=true \
               --secure-port=6443 \
               --storage-backend=etcd3 \
               --allow-privileged=true \
               --v=4 \
          1>>/var/log/kube-apiserver.log 2>&1
      livenessProbe:
        httpGet:
          host: 127.0.0.1
          port: 8080
          path: /healthz
        initialDelaySeconds: 15
        timeoutSeconds: 15
      ports:
        - name: https
          containerPort: 6443
          hostPort: 6443
        - name: local
          containerPort: 8080
          hostPort: 8080
      volumeMounts:
        - name: logfile
          mountPath: /var/log/kube-apiserver.log
          readOnly: false
        - name: auditlogfile
          mountPath: /var/log/kube-apiserver-audit.log
          readOnly: false
        - name: etcssl
          mountPath: /etc/ssl
          readOnly: true
        - name: etcpki
          mountPath: /etc/pki
          readOnly: true
        - mountPath: /etc/kubernetes/
          name: kubeconfig
          readOnly: false
  volumes:
    - name: logfile
      hostPath:
        path: /var/log/kube-apiserver.log
        type: FileOrCreate
    - name: auditlogfile
      hostPath:
        path: /var/log/kube-apiserver-audit.log
        type: FileOrCreate
    - name: etcssl
      hostPath:
        path: /etc/ssl
    - name: etcpki
      hostPath:
        path: /etc/pki
    - name: kubeconfig
      hostPath:
        path: /etc/kubernetes/
