apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
  labels:
    tier: control-plane
    component: kube-controller-manager
spec:
  hostNetwork: true
  containers:
    - name: kube-controller-manager
      image: "k8s.gcr.io/hyperkube:{{KUBE_RELEASE}}"
      resources:
        requests:
          cpu: 200m
      command:
        - /bin/sh
        - '-c'
        - |
          exec /usr/local/bin/kube-controller-manager \
                  --master=127.0.0.1:8080 \
                  --cluster-name={{CLUSTER}} \
                  --service-account-private-key-file=/etc/kubernetes/ca/ca-key.pem \
                  --root-ca-file=/etc/kubernetes/ca/ca.pem \
                  --cluster-signing-cert-file=/etc/kubernetes/ca/ca.pem \
                  --cluster-signing-key-file=/etc/kubernetes/ca/ca-key.pem \
                  --service-cluster-ip-range={{SERVICE_CIDR}}
                  --cluster-cidr={{CLUSTER_CIDR}}
                  --v=2 \
          1>>/var/log/kube-controller-manager.log 2>&1
      livenessProbe:
        httpGet:
          host: 127.0.0.1
          port: 10252
          path: /healthz
        initialDelaySeconds: 15
        timeoutSeconds: 15
      volumeMounts:
        - name: kubeconfig
          mountPath: /etc/kubernetes/
          readOnly: false
        - name: logfile
          mountPath: /var/log/kube-controller-manager.log
          readOnly: false
        - name: etcssl
          mountPath: /etc/ssl
          readOnly: true
        - name: etcpki
          mountPath: /etc/pki
          readOnly: true
  volumes:
    - name: kubeconfig
      hostPath:
        path: /etc/kubernetes/
    - name: logfile
      hostPath:
        path: /var/log/kube-controller-manager.log
        type: FileOrCreate
    - name: etcssl
      hostPath:
        path: /etc/ssl
    - name: etcpki
      hostPath:
        path: /etc/pki
